version: '3'

services:

  ########################
  # third-party backends #
  ########################

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: "zookeeper"
    ports:
      - 2181:2181

  kafka:
    image: wurstmeister/kafka:2.11-1.1.1
    container_name: "kafka"
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      LOG4J_LOGGER_KAFKA: INFO
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.1
    container_name: "elasticsearch"
    environment:
      - discovery.type=single-node
      - cluster.name=elasticsearch
    ports:
      - 9200:9200
      - 9300:9300

  mongodb:
    image: mongo:3.4
    container_name: "mongodb"
    ports:
      - 27017:27017

  #########
  # ARLAS #
  #########

  arlas-server:
    image: gisaia/arlas-server:11.6.0
    container_name: "arlas-server"
    ports:
      - 9999:9999
    depends_on:
      - elasticsearch
    environment:
      ARLAS_ELASTIC_CLUSTER: elasticsearch
      ARLAS_ELASTIC_NODES: elasticsearch:9300
    command: ["/opt/app/wait-for-elasticsearch.sh"]

  arlas-subscriptions-matcher:
    build:
      context: .
      dockerfile: Dockerfile-matcher
    image: arlas-subscriptions-matcher:latest
    container_name: "arlas-subscriptions-matcher"
    depends_on:
      - arlas-server
      - kafka
    environment:
      - KAFKA_BROKERS=kafka:9092
      - ARLAS_ELASTIC_NODES=elasticsearch:9300
      - ARLAS_SERVER=arlas-server:9999
      - ARLAS_SERVER_BASE_PATH=http://arlas-server:9999
      - ARLAS_SUBSCRIPTIONS_BASE_PATH=http://arlas-server:9999
    command: ["/opt/app/wait-for-deps.sh $$KAFKA_BROKERS $$ARLAS_ELASTIC_NODES $$ARLAS_SERVER"]

  arlas-subscriptions-manager:
    build:
      context: .
      dockerfile: Dockerfile-manager
    image: arlas-subscriptions-manager:latest
    container_name: "arlas-subscriptions-manager"
    depends_on:
      - mongodb
      - elasticsearch
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - ARLAS_SUB_ELASTIC_NODES=elasticsearch:9300
      - ARLAS_SUB_ELASTIC_INDEX=subs
      - ARLAS_SUB_ELASTIC_TYPE=sub_type
    ports:
      - 9998:9998
    command: ["/opt/app/wait-for-deps.sh $$MONGO_HOST:$$MONGO_PORT $$ARLAS_SUB_ELASTIC_NODES "]