FROM gisaia/arlas-openjdk-17-dhi:20260505130838

# application placed into /opt/app
WORKDIR /opt/app
ADD subscriptions-manager/target/subscriptions-manager*.jar /opt/app/subscriptions-manager.jar
ADD conf/configuration-manager.yaml /opt/app/configuration-manager.yaml

CMD ["java", "-jar", "/opt/app/subscriptions-manager.jar", "server", "/opt/app/configuration-manager.yaml"]