FROM openjdk:8-jre-alpine

# install script dependencies
RUN apk add --update bash netcat-openbsd curl && rm -rf /var/cache/apk/*

# application placed into /opt/app
WORKDIR /opt/app
ADD subscriptions-manager/target/subscriptions-manager*.jar /opt/app/subscriptions-manager.jar
ADD conf/configuration-manager.yaml /opt/app/configuration-manager.yaml
ADD subscriptions-manager/scripts/wait-for-deps.sh /opt/app/wait-for-deps.sh

ENTRYPOINT ["bash", "-c"]
CMD ["java -jar /opt/app/subscriptions-manager.jar server /opt/app/configuration-manager.yaml"]
