FROM gisaia/arlas-openjdk:17-distroless

# application placed into /opt/app
WORKDIR /opt/app
ADD subscriptions-manager/target/subscriptions-manager*.jar /opt/app/subscriptions-manager.jar
ADD conf/configuration-manager.yaml /opt/app/configuration-manager.yaml

CMD ["subscriptions-manager.jar", "server", "/opt/app/configuration-manager.yaml"]
