<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.arlas</groupId>
        <artifactId>subscriptions-parent</artifactId>
        <version>24.0.6-SNAPSHOT</version>
    </parent>
    <artifactId>subscriptions-commons</artifactId>
    <packaging>jar</packaging>
    <name>ARLAS subscriptions commons</name>
    <dependencies>
        <dependency>
            <groupId>io.arlas</groupId>
            <artifactId>arlas-admin</artifactId>
            <version>${arlas.version}</version>
        </dependency>

        <!-- UUID generator -->
        <dependency>
            <groupId>com.fasterxml.uuid</groupId>
            <artifactId>java-uuid-generator</artifactId>
            <version>${jug.version}</version>
            <exclusions>
                <exclusion>
                    <artifactId>slf4j-api</artifactId>
                    <groupId>org.slf4j</groupId>
                </exclusion>
            </exclusions>
        </dependency>
    </dependencies>
</project>