apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "arlas-subscriptions.fullname" . }}-arlas-sub-server
  labels:
{{ include "arlas-subscriptions.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.server.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "arlas-subscriptions.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "arlas-subscriptions.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: server
    spec:
      containers:
        - name: container
          env:
            - name: ARLAS_ELASTIC_CLUSTER
              value: {{ .Values.elasticsearch.cluster }}
            - name: ARLAS_ELASTIC_NODES
              value: {{ .Values.elasticsearch.endpoints.transport | join "," }}
          {{- if .Values.server.environmentVariables }}
            {{- include "arlas-subscriptions.server.environmentVariables" . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.server.image.repository }}:{{ .Values.server.image.tag }}"
          imagePullPolicy: {{ .Values.server.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.server.environmentVariables.ARLAS_PORT }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /admin/healthcheck
              port: http
            initialDelaySeconds: {{ .Values.server.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.server.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.server.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.server.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.server.livenessProbe.failureThreshold }}
          readinessProbe:
            httpGet:
              path: /admin/healthcheck
              port: http
            initialDelaySeconds: {{ .Values.server.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.server.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.server.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.server.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.server.readinessProbe.failureThreshold }}
          resources:
            {{- toYaml .Values.server.resources | nindent 12 }}
    {{- if .Values.server.imagePullSecrets }}
      imagePullSecrets:
      {{- include "arlas-subscriptions.server.imagePullSecrets" . | nindent 8 }}
    {{- end }}
      {{- with .Values.server.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.server.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.server.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
