apiVersion: v1
kind: Service
metadata:
  name: {{ include "arlas-subscriptions.server.service.name" . }}
  labels:
{{ include "arlas-subscriptions.labels" . | indent 4 }}
    app.kubernetes.io/component: server
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "arlas-subscriptions.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: server