trigger:
  trigger-geometry-key: ${ARLAS_SUB_GEOM_KEY:-geometry}
  trigger-centroid-key: ${ARLAS_SUB_CENT_KEY:-centroid}

########################################################
######################### IDENTITY #####################
########################################################

identity:
  identity-header: ${ARLAS_SUB_IDENTITY_HEADER:-}
  identity-admin: ${ARLAS_SUB_IDENTITY_ADMIN:-admin}

########################################################
############ SWAGGER                     ###############
########################################################
#
swagger: # Configuration of SWAGGER for generating documentation and APIs
  resourcePackage: io.arlas.subscriptions.rest # The java package to process for extracting the APIs
  # temporary patch for bug https://github.com/smoketurner/dropwizard-swagger/issues/206
  # to be removed when version of dropwizard.swagger.version is upgraded
  customJavascript: ${ARLAS_SUB_CUSTOM_JS:-/arlas/swagger-static/custom-request-interceptor.js}

########################################################
############ HTTP SERVER                 ###############
########################################################
# Configuration of the HTTP Server and of the HTTP ACCESS LOGGING
server:
  requestLog:
    appenders:
      - type: file
        currentLogFilename: ${ARLAS_SUB_MANAGER_ACCESS_LOG_FILE:-arlas-sub-manager-access.log}
        archivedLogFilenamePattern: ${ARLAS_SUB_MANAGER_ACCESS_LOG_FILE_ARCHIVE:-arlas-sub-manager-access-%d.log.gz}
  registerDefaultExceptionMappers: false
  type: simple
  rootPath: ${ARLAS_SUB_MANAGER_PREFIX:-/arlas-subscriptions-manager}
  applicationContextPath: ${ARLAS_SUB_MANAGER_APP_PATH:-/}
  adminContextPath: ${ARLAS_SUB_MANAGER_ADMIN_PATH:-/admin}
  connector:
    type: http
    port: ${ARLAS_SUB_MANAGER_PORT:-9998}
  maxThreads: ${ARLAS_SUB_MANAGER_MAX_THREADS:-1024}
  minThreads: ${ARLAS_SUB_MANAGER_MIN_THREADS:-8}
  maxQueuedRequests: ${ARLAS_SUB_MANAGER_MAX_QUEUED_REQUESTS:-1024}

########################################################
############ LOGGING                     ###############
########################################################
# Configuration console and file LOGGING
logging:
  level: ${ARLAS_SUB_MANAGER_LOGGING_LEVEL:-INFO}
  appenders:
    - type: console
      threshold:  ${ARLAS_SUB_MANAGER_LOGGING_CONSOLE_LEVEL:-INFO}
    - type: file
      currentLogFilename: ${ARLAS_SUB_MANAGER_LOGGING_FILE:-arlas.log}
      threshold: ${ARLAS_SUB_MANAGER_LOGGING_FILE_LEVEL:-INFO}
      archive: ${ARLAS_SUB_MANAGER_LOGGING_FILE_ARCHIVE:-true}
      archivedLogFilenamePattern: ${ARLAS_SUB_MANAGER_LOGGING_FILE_ARCHIVE_FILE_PATTERN:-arlas-%d.log}
      archivedFileCount: ${ARLAS_SUB_MANAGER_LOGGING_FILE_ARCHIVE_FILE_COUNT:-5}

mongo:
  seeds: ${MONGO_HOST:-mongodb:27017}
  database: ${MONGO_DATABASE:-subscription}
  username: ${MONGO_USERNAME:-}
  password: ${MONGO_PASSWORD:-}
  authDatabase: ${MONGO_AUTH_DATABASE:-}


########################################################
############ DATASOURCE                  ###############
########################################################
# Configuration of the datasource
elastic:
  elastic-nodes: ${ARLAS_SUB_ELASTIC_NODES:-localhost:9200}
  elastic-enable-ssl: ${ARLAS_SUB_ELASTIC_ENABLE_SSL:-false}
  elastic-credentials: ${ARLAS_SUB_ELASTIC_CREDENTIALS}
  elastic-socket-timeout: ${ARLAS_ELASTIC_SOCKET_TIMEOUT:-30000}
  elastic-max-precision-threshold: ${ARLAS_ELASTIC_MAX_PRECISON_THRESHOLD:-3000}
  index:  ${ARLAS_SUB_ELASTIC_INDEX:-subscription}
  bulk:
    concurrent-requests: ${ARLAS_SUB_ELASTIC_CONCURRENT_REQUESTS:-1}
    bulk-actions: ${ARLAS_SUB_ELASTIC_BULK_ACTIONS:-10000}
    bulk-size: ${ARLAS_SUB_ELASTIC_BULK_SIZE:-5} # in MB
    flush-interval: ${ARLAS_SUB_ELASTIC_FLUSH_INTERVAL:-5000} # in ms
    backoff-delay: ${ARLAS_SUB_ELASTIC_BACKOFF_DELAY:-100} # in ms
    backoff-retries: ${ARLAS_SUB_ELASTIC_BACKOFF_UNIT:-3}

