#################################################
############ KAFKA                ###############
#################################################
kafka:
  kafka-consumer-poll-timeout: ${KAFKA_CONSUMER_POLL_TIMEOUT:-100}
  kafka-batch-size: ${KAFKA_BATCH_SIZE:-10}
  kafka-bootstrap-servers: ${KAFKA_BROKERS:-kafka:9092}
  kafka-consumer-group-id: ${KAFKA_CONSUMER_GROUP_ID:-subscription_events_consumer_group}
  kafka-topic-subscription-events: ${KAFKA_TOPIC_SUBSCRIPTION_EVENTS:-subscription_events}
  kafka-topic-notification-orders: ${KAFKA_TOPIC_NOTIFICATION_ORDERS:-notification_orders}

#################################################
############ ARLAS ENDPOINTS      ###############
#################################################

arlas-subscriptions-basePath: ${ARLAS_SUBSCRIPTIONS_BASE_PATH:-http://localhost:9999}
arlas-subscriptions-searchEndpoint: ${ARLAS_SUBSCRIPTIONS_SEARCH_ENDPOINT:-/arlas/explore/subscriptions/_search}
arlas-subscriptions-subscriptionFilterRoot: gintersect={md.geometry}&f=subscription.trigger.event:eq:{operation}&f=subscription.trigger.job:eq:{collection}&f=active:eq:true&f=deleted:eq:false&f=expires_at:gt:now&f=starts_at:lte:now&sort=id

arlas-server-basePath: ${ARLAS_SERVER_BASE_PATH:-http://localhost:9999}
arlas-server-searchEndpoint: ${ARLAS_SERVER_SEARCH_ENDPOINT:-/arlas/explore/geodata/_search}
arlas-server-hitFilterRoot: f=id:eq:{md.id}


########################################################
############ SWAGGER                     ###############
########################################################
#
swagger: # Configuration of SWAGGER for generating documentation and APIs
  resourcePackage: io.arlas.subscriptions.rest # The java package to process for extracting the APIs

########################################################
############ HTTP SERVER                 ###############
########################################################
# Configuration of the HTTP Server and of the HTTP ACCESS LOGGING
server:
  requestLog:
    appenders:
      - type: file
        currentLogFilename: ${ARLAS_SUB_MANAGER_ACCESS_LOG_FILE:-arlas-sub-manager-access.log}
        archivedLogFilenamePattern: ${ARLAS_SUB_MANAGER_ACCESS_LOG_FILE_ARCHIVE:-arlas-sub-manager-access-%d.log.gz}
  registerDefaultExceptionMappers: false
  type: simple
  rootPath: ${ARLAS_SUB_MANAGER_PREFIX:-/arlas-subscriptions-manager}
  applicationContextPath: ${ARLAS_SUB_MANAGER_APP_PATH:-/}
  adminContextPath: ${ARLAS_SUB_MANAGER_ADMIN_PATH:-/admin}
  connector:
    type: http
    port: ${ARLAS_SUB_MANAGER_PORT:-9998}
  maxThreads: ${ARLAS_SUB_MANAGER_MAX_THREADS:-1024}
  minThreads: ${ARLAS_SUB_MANAGER_MIN_THREADS:-8}
  maxQueuedRequests: ${ARLAS_SUB_MANAGER_MAX_QUEUED_REQUESTS:-1024}

########################################################
############ ZIPKIN                      ###############
########################################################
# Zipkin let you analyze the API calls
zipkin: # The ZIPIN configuration, not active by default
  enabled: ${ARLAS_SUB_MANAGER_ZIPKIN_ENABLED:-false} # Do we want zipkin to collect the API calls? Not by default.
  serviceHost: ${ARLAS_SUB_MANAGER_ZIPKIN_SERVICE_HOST:-127.0.0.1} # Listening IP address of the service
  servicePort: ${ARLAS_SUB_MANAGER_PORT:-9998} # Listening port of the service
  collector: ${ARLAS_SUB_MANAGER_ZIPKIN_COLLECTOR:-http}
  baseUrl: ${ARLAS_SUB_MANAGER_ZIPKIN_BASEURL:-http://localhost:9411} # Where is zipkin running?

########################################################
############ LOGGING                     ###############
########################################################
# Configuration console and file LOGGING
logging:
  level: ${ARLAS_SUB_MANAGER_LOGGING_LEVEL:-INFO}
  appenders:
    - type: console
      threshold:  ${ARLAS_SUB_MANAGER_LOGGING_CONSOLE_LEVEL:-INFO}
    - type: file
      currentLogFilename: ${ARLAS_SUB_MANAGER_LOGGING_FILE:-arlas.log}
      threshold: ${ARLAS_SUB_MANAGER_LOGGING_FILE_LEVEL:-INFO}
      archive: ${ARLAS_SUB_MANAGER_LOGGING_FILE_ARCHIVE:-true}
      archivedLogFilenamePattern: ${ARLAS_SUB_MANAGER_LOGGING_FILE_ARCHIVE_FILE_PATTERN:-arlas-%d.log}
      archivedFileCount: ${ARLAS_SUB_MANAGER_LOGGING_FILE_ARCHIVE_FILE_COUNT:-5}

mongo:
  seeds:
    - host: ${MONGO_HOST:-mongodb}
      port: ${MONGO_PORT:-27017}
  database: ${MONGO_DATABASE:-subscription}


########################################################
############ DATASOURCE                  ###############
########################################################
# Configuration of the datasource
elastic:
  nodes: ${ARLAS_SUB_ELASTIC_NODES:-localhost:9300}
  sniffing: ${ARLAS_SUB_ELASTIC_SNIFFING:-false}
  cluster: ${ARLAS_SUB_ELASTIC_CLUSTER:-elasticsearch}
  index:  ${ARLAS_SUB_ELASTIC_INDEX:-subscription}
  type: ${ARLAS_SUB_ELASTIC_TYPE:-sub_type}

########################################################
############ Subcription DATA model      ###############
########################################################
trigger-geometry-key: ${ARLAS_SUB_GEOM_KEY:-geometry}
trigger-centroid-key: ${ARLAS_SUB_CENT_KEY:-centroid}

identity-header: ${ARLAS_SUB_IDENTITY_HEADER:-}
identity-admin: ${ARLAS_SUB_IDENTITY_ADMIN:-admin}