#################################################
############ KAFKA                ###############
#################################################
kafka:
  kafka-consumer-poll-timeout: ${KAFKA_CONSUMER_POLL_TIMEOUT:-100}
  kafka-batch-size: ${KAFKA_BATCH_SIZE:-10}
  kafka-bootstrap-servers: ${KAFKA_BROKERS:-kafka:9092}
  kafka-consumer-group-id: ${KAFKA_CONSUMER_GROUP_ID:-subscription_events_consumer_group}
  kafka-topic-subscription-events: ${KAFKA_TOPIC_SUBSCRIPTION_EVENTS:-subscription_events}
  kafka-topic-notification-orders: ${KAFKA_TOPIC_NOTIFICATION_ORDERS:-notification_orders}

arlas-subscriptions-basePath: ${ARLAS_SUBSCRIPTIONS_BASE_PATH:-http://localhost}
arlas-subscriptions-searchEndpoint: ${ARLAS_SUBSCRIPTIONS_SEARCH_ENDPOINT:-/explore/subscription/_search}
arlas-subscriptions-subscriptionFilterRoot: gintersect={md.geometry}&f=subscription.trigger.operations:eq:{operation}&f=subscription.trigger.collection:eq:{collection}&f=active:eq:true&f=deleted:eq:false&f=expires_at:gt:now&sort=id

arlas-server-basePath: ${ARLAS_SERVER_BASE_PATH:-http://localhost}
arlas-server-searchEndpoint: ${ARLAS_SERVER_SEARCH_ENDPOINT:-/api/v1/services/search}
arlas-server-hitFilterRoot: f=uid:eq:{md.id}


########################################################
############ SWAGGER                     ###############
########################################################
#
swagger: # Configuration of SWAGGER for generating documentation and APIs
  resourcePackage: io.arlas.subscriptions.rest # The java package to process for extracting the APIs

########################################################
############ HTTP SERVER                 ###############
########################################################
# Configuration of the HTTP Server and of the HTTP ACCESS LOGGING
server:
  requestLog:
    appenders:
      - type: file
        currentLogFilename: ${ARLAS_ACCESS_LOG_FILE:-arlas-access.log}
        archivedLogFilenamePattern: ${ACCESS_LOG_FILE_ARCHIVE:-arlas-access-%d.log.gz}
  registerDefaultExceptionMappers: false
  type: simple
  rootPath: ${ARLAS_PREFIX:-/arlas-subscriptions-manager}
  applicationContextPath: ${ARLAS_APP_PATH:-/}
  adminContextPath: ${ARLAS_ADMIN_PATH:-/admin}
  connector:
    type: http
    port: ${ARLAS_PORT:-9998}
  maxThreads: ${ARLAS_MAX_THREADS:-1024}
  minThreads: ${ARLAS_MIN_THREADS:-8}
  maxQueuedRequests: ${ARLAS_MAX_QUEUED_REQUESTS:-1024}

########################################################
############ ZIPKIN                      ###############
########################################################
# Zipkin let you analyze the API calls
zipkin: # The ZIPIN configuration, not active by default
  enabled: ${ARLAS_ZIPKIN_ENABLED:-false} # Do we want zipkin to collect the API calls? Not by default.
  serviceHost: ${ARLAS_ZIPKIN_SERVICE_HOST:-127.0.0.1} # Listening IP address of the service
  servicePort: ${ARLAS_PORT:-9998} # Listening port of the service
  collector: ${ARLAS_ZIPKIN_COLLECTOR:-http}
  baseUrl: ${ARLAS_ZIPKIN_BASEURL:-http://localhost:9411} # Where is zipkin running?

########################################################
############ LOGGING                     ###############
########################################################
# Configuration console and file LOGGING
logging:
  level: ${ARLAS_LOGGING_LEVEL:-INFO}
  appenders:
    - type: console
      threshold:  ${ARLAS_LOGGING_CONSOLE_LEVEL:-INFO}
    - type: file
      currentLogFilename: ${ARLAS_LOGGING_FILE:-arlas.log}
      threshold: ${ARLAS_LOGGING_FILE_LEVEL:-INFO}
      archive: ${ARLAS_LOGGING_FILE_ARCHIVE:-true}
      archivedLogFilenamePattern: ${ARLAS_LOGGING_FILE_ARCHIVE_FILE_PATTERN:-arlas-%d.log}
      archivedFileCount: ${ARLAS_LOGGING_FILE_ARCHIVE_FILE_COUNT:-5}


mongo:
  seeds:
    - host: ${MONGO_HOST:-mongodb}
      port: ${MONGO_PORT:-mongodb}
  database: ${MONGO_DATABASE:-subscription}