apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "arlas-subscriptions.manager.triggerSchema.configMap" . }}
  labels:
{{ include "arlas-subscriptions.labels" . | indent 4 }}
data:
  {{ base .Values.manager.triggerSchema.path }}: |
{{ .Values.manager.triggerSchema.content | toPrettyJson | nindent 4 }}
