name: Run Trivy
run-name: Run Trivy - Vulnerability Scan

on:
  push:
  schedule:
    # At 05:15 UTC on day-of-month 2
    - cron: '15 5 2 * *'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Maven # From https://github.com/actions/cache/blob/main/examples.md
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build artifact
        run: mvn clean package

      - name: Build an image from Dockerfile
        run: |
          docker build -f Dockerfile-manager -t docker.io/gisaia/arlas-subscriptions-manager:${{ github.sha }} .
          docker build -f Dockerfile-matcher -t docker.io/gisaia/arlas-subscriptions-matcher:${{ github.sha }} .

      - name: Run Trivy vulnerability scanner on Manager
        uses: aquasecurity/trivy-action@master
        env:
          TRIVY_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-db:2
          TRIVY_JAVA_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-java-db:1
        with:
          image-ref: 'docker.io/gisaia/arlas-subscriptions-manager:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: false
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          trivyignores: .github/workflows/.trivyignore

      - name: Run Trivy vulnerability scanner on Matcher
        uses: aquasecurity/trivy-action@master
        env:
          TRIVY_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-db:2
          TRIVY_JAVA_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-java-db:1
        with:
          image-ref: 'docker.io/gisaia/arlas-subscriptions-matcher:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: false
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          trivyignores: .github/workflows/.trivyignore
      - name: Notify Google Chat
        if: ${{ always() }} # Use always to ensure that the notification is also send on failure of former steps
        uses: SimonScholz/google-chat-action@main
        with:
          webhookUrl: '${{ secrets.GOOGLE_CHAT_SCAN_CHANEL }}'
          jobStatus: '${{ job.status }}'
          title: 'Trivy Scan on ARLAS-subscriptions'
